### PR TITLE
New Components for doc headers & data types. Updated docs

### PR DESCRIPTION
**Pull request by MatthewAry**
This PR includes multiple improvements:
- Turns the data types table into a reusable component so it can be displayed on both the data model overview page and on the Define Field Statement page.
- Adds a new component to create h1-h6 tags with more conventional font sizes, page anchoring, anchor link copying.
- Implements the new header component across many of the docs (but currently not all of them) but the initial commit for this pr does not add IDs to the elements to enable the page anchoring feature.
- Makes mention that you can actually cast a value to a record on the casting page but does not provide examples.

### CODE REVIEW

**Comment by MatthewAry** [comment]
This now touches almost all of the documentation.

**Comment by MatthewAry** [comment]
In summary, this PR strives to make the H1-H6 tags usefuln in docs as they were being used more for aesthetic convenience instead of their original purpose. I created a component that will use the H tags and apply a class to them that will apply a more conventional style to them. This component also has additional features, allowing you to make a page anchor and copy a link to the page + anchor for convenience in developer communications.

Authors of the existing documentation were using the H tags correctly, but they were getting displayed with inconsistent font sizes and styles.

While it is typically frowned upon to make gigantic PRs, this change should be welcomed as it should also improve DX for SurrealDB developer users.

**Comment by Ekwuno** [comment]
@MatthewAry firstly thanks for opening this PR, while it does solve a DX issue regarding hyperlinking in docs, a couple of things to point out. 

1. Generally we take a discussion -> Issue -> PR  approach with PRs, especially huge  ones. This  allows for us to agree on how to move forward and to confirm if the PR isn't already being worked on. 

2. I mentioned that we are currently in the process of moving the documentation to another service that comes with these kind of features out of the box and also allows contributions in markdown and better DX. This solution has been implemented in the migration. 

3. Also 101 file changes for 1 PR is a lot 🥲, we ask that PRs be kept to functional changes. In this case, one to add the component, other chunks to implement them.

**Comment by MatthewAry** [comment]
I would be happy to help out with the migration and helping build the new site. I consider myself to be pretty good at front-end stuff.

**Comment by Ekwuno** [comment]
@MatthewAry I am going to be closing this PR for now. Thank you for contributing. In the future for these kinds of PR please  lets open an issue to communicate scope and see if this is already being worked on. 💜

**Pull request closed without merging**
