### PR TITLE
Full-text search documentation

### PR DESCRIPTION
**Pull request by emmanuel-keller**
Page with changes:

http://localhost:4200/features
http://localhost:4200/docs/surrealql/statements/define
http://localhost:4200/docs/surrealql/statements/define/analyzer
http://localhost:4200/docs/surrealql/statements/define/indexes
http://localhost:4200/docs/surrealql/operators#matches

### CODE REVIEW

**Comment by kearfy** [comment]
@sgirones any idea what happened to the Netlify deployment here?

**Comment by Ekwuno** [comment]
> @sgirones any idea what happened to the Netlify deployment here?

@kearfy it works as it should. I think Emmanuel deleted the preview details. Another commit should trigger it or going to the Netlify console for this particular branch will show the preview URL

**Comment by emmanuel-keller** [comment]
> > @sgirones any idea what happened to the Netlify deployment here?
> 
> @kearfy it works as it should. I think Emmanuel deleted the preview details. Another commit should trigger it or going to the Netlify console for this particular branch will show the preview URL

Yes I did it because I noticed it didn't refresh after I force pushed the branch :(

**Comment by kearfy** [comment]
I'll just run locally haha

**Pull request merged**
