### PR TITLE
Adding Docs for Amazon EKS

### PR DESCRIPTION
**Pull request by giusedroid**
Hey SurrealDB team!

I've written an article about how to deploy SurrealDB on Amazon EKS backed by TiKV in HA configuration!  
Happy building!

### CODE REVIEW

**Comment by naisofly** [comment]
@giusedroid Thanks for this AWS Deployment guide 🙌 Really appreciate your contribution here 🙏 
At the start of the guide, we can add a one-liner introduction before the "What is Amazon EKS?" section. 

Something like:
"This guide shows you how to set up a highly available SurrealDB cluster backed by TiKV on Amazon EKS."

FYI @sgirones

**Comment by giusedroid** [comment]
Happy to folks! We'd love to see customers running SurrealDB on AWS <3

**Comment by Ekwuno** [comment]
@giusedroid I did a bit of structure cleanup on this, if you're ok with it we can move on and get this merged.  let us know.

**Comment by giusedroid** [comment]
Looks good to me! Thanks!

**Pull request merged**
