### PR TITLE
Delete relations

### PR DESCRIPTION
**Pull request by RaphaelDarley**
adding details on how to delete relations to resolve surrealdb/surrealdb#1363

### CODE REVIEW

**Review by Ekwuno — APPROVED** [review]
LGTM!

**Comment by kearfy** [comment]
I would like to point out here that the example shown here will also delete duplicate relations (which can exist if somebody does not use an index to prevent such a thing from happening)

If somebody wants to delete a specific relation they would need to do that by it's ID

**Comment by Ekwuno** [comment]
@kearfy I am not sure. If the `bought` relation is unique and we have a unique recordID won't that avoid duplicates? The example shows that these are unique. 

Are you suggesting stating in this section that these parameters have to be unique? I updated this PR [here](https://surrealdb.com/docs/surrealql/statements/delete)

**Comment by naisofly** [comment]
@Ekwuno To the Delete Graph Edges section,

Should we also mention (as suggested in the initial issue), both the following commands work:

"The relation is basically just a table called likes with an in and an out so you can delete it as normal:"

```
DELETE bought WHERE in=user:tobieAND out=product:iphone;
DELETE person:tobie->bought WHERE out=product:iphone;
```

**Pull request merged**
