### PR TITLE
Update Rust SDK docs to explain how to retrieve JWT

### LINKED ISSUE #205: [beta-10] Update Rust SDK docs to explain how to retrieve JWT
Per this change https://github.com/surrealdb/surrealdb/pull/2215

### PR DESCRIPTION
**Pull request by Odonno**
Closes #205 

Side note: Is it normal that rust code example files have a `.rust` extension instead of a `.rs` extension?

### CODE REVIEW

**Comment by Ekwuno** [comment]
@Odonno thanks for picking this up. I am not sure if the extensions should be `.rust`  or `.rs`. Either works right?

**Review by Ekwuno — APPROVED** [review]
LGTM

**Comment by Odonno** [comment]
> @Odonno thanks for picking this up. I am not sure if the extensions should be `.rust` or `.rs`. Either works right?

`.rs` is the right extension and it is detected by VS Code. `.rust` is not.

**Comment by Ekwuno** [comment]
> > @Odonno thanks for picking this up. I am not sure if the extensions should be `.rust` or `.rs`. Either works right?
> 
> `.rs` is the right extension and it is detected by VS Code. `.rust` is not.

Gotcha! We do say open a `src/main/rs` file in the docs. Migrating the docs now and will include the proper extention in the code snippet title.

**Pull request merged**
