### PR TITLE
Documents vector functions

### PR DESCRIPTION
**Pull request by emmanuel-keller**
This PR documents the new vector functions implemented here: https://github.com/surrealdb/surrealdb/pull/2266

### CODE REVIEW

**Comment by kearfy** [comment]
@emmanuel-keller as we discovered elsewhere, some of these functions returning an array instead of a number is actually caused by the CLI, could you change the output of these functions to be just a number?

Besides that it looks good to me! Could you change the base of the branch to the #197 PR? We collect all the beta-10 doc changes in there. You might need to rebase

**Comment by Ekwuno** [comment]
@emmanuel-keller alternatively you can close this PR and push the changes you've made to the beta-10 branch. 

The content LGTM!. Thanks for adding this in.

**Comment by Ekwuno** [comment]
Ah disregard last comment. Since it doesn't have all the commits from main.

**Comment by Ekwuno** [comment]
> > Ah disregard last comment. Since it doesn't have all the commits from main.
> 
> 
> 
> @kearfy  ~~It should be okay now, if you just refresh, you should only see 4 commits, right?~~
> 
> 
> 
> ??

Yes yes! All good now!

**Review by kearfy — APPROVED** [review]

**Pull request merged**
