### PR TITLE
Minimal changes on start page steps 2-8 and starting-surrealdb page

### PR DESCRIPTION
**Pull request by koakh**
- replaced `curl -k -L -s --compressed`with `curl -s`. we don't need --compressed anymore in surreal-v1.0.0-beta.5
- added multi-node distributed database with persistence storage notes

### CODE REVIEW

**Comment by tobiemh** [comment]
Hey @koakh sorry I only just saw this. I made a number of changes which cover some of these things (multi-node with persistence). Is it possible to redo this commit, rebasing from main?

**Comment by koakh** [comment]
Yes sure Tobie

Send me the changed pages
If you want I'm glad to test it to double check that everything is smoth

⁣Koakh

On Aug 4, 2022, 12:53, at 12:53, Tobie Morgan Hitchcock ***@***.***> wrote:
>Hey @koakh sorry I only just saw this. I made a number of changes which
>cover some of these things (multi-node with persistence). Is it
>possible to redo this commit, rebasing from main?
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/surrealdb/www.surrealdb.com/pull/12#issuecomment-1205152908
>You are receiving this because you were mentioned.
>
>Message ID:
***@***.***>

**Comment by tobiemh** [comment]
Hey @koakh I closed this, as there are quite a few changes since this pull-request, resulting in some conflicts. Also there are quite a few changes coming to the docs, which will make this obsolete 😀!

**Comment by koakh** [comment]
Roger that !

**Pull request closed without merging**
